### ISSUE TITLE
Error thrown when running 

### ISSUE THREAD

**Issue by multum-non-multa** [ddd-Makbema/gameEngine#21]
I wanted you to see what I get when I run 

```bash
python main.py

```

```bash
Traceback (most recent call last):
  File "gameEngine/game_object.py", line 158, in _import_class_from_string
    mod = __import__(mod_name)
ModuleNotFoundError: No module named 'scripts.builtins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from variables import screen
  File "gameEngine/variables.py", line 6, in <module>
    GO("collision handler", screen.screen, "null.png", "origin", "Collider2D.CollisionHandler")
  File "gameEngine/game_object.py", line 60, in __init__
    tempInst = self._import_class_from_string(full_module_name, user_module_name)(self)
  File "gameEngine/game_object.py", line 164, in _import_class_from_string
    mod = __import__(mod_name)
ModuleNotFoundError: No module named 'scripts.user'

```

**Comment by multum-non-multa** [comment]
Each directory in `scripts` need to have a `__init__.py` 

Will implement and test
